### ISSUE TITLE
UI Bug: App-Name overflows tile if very long

### ISSUE THREAD

**Issue by In-Ko** [gardener/potter-hub#10]
**Description**
If the app-name of an appplication exeeds a certain amount of characters, it overflows the tile (see screenshot).
This needs to be fixed.

![image](https://user-images.githubusercontent.com/37654232/109494462-3a7ac080-7a8e-11eb-9fe3-c69b1318eb35.png)

**Comment by enrico-kaack-comp** [comment]
Fixed: 

![image](https://user-images.githubusercontent.com/72856950/111297044-76488500-864d-11eb-8729-8f82f85f0ed7.png)

Use mouseover to see the tooltip with the full version.
